name: yuumAI

run-name: PR checker

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.14.0"
      - run: cd front-end
      - run: npm ci
      - run: npm run lint
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Node.js setup
        uses: actions/setup-node@v3
        with:
          node-version: "22.14.0"
          cache: "npm"
      - run: cd front-end
      - run: npm ci
      - run: npm run build
  
  